about/urls.py
from django.urls import path
from . import views

app_name = 'about'

urlpatterns = [

    path('',views.about,name='about'),
    
]

accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [

    path('register/',views.register,name='register'),
    path('login/',views.login_view,name='login'),
    path('logout/',views.logout_view,name='logout'),
    path('edit_profile/',views.edit_profile,name='edit_profile'),
    path('reset_password/',views.reset_password,name='reset_password'),
    path('profile/',views.profile,name='profile'),
    
]

contact/urls.py
from django.urls import path
from . import views

app_name = 'contact'

urlpatterns = [

    path('',views.contact,name='contact'),
    
]

course/urls.py
from django.urls import path
from . import views

app_name = 'courses'

urlpatterns = [

    path('',views.course,name='course'),
    
]

pages/urls.py
from django.urls import path
from . import views

app_name = 'pages'

urlpatterns = [

    path('write_comment/',views.write_comment,name='write_comment'),
    path('testimonial/',views.testimonial,name='testimonial'),
    path('features/',views.features,name='features'),
    path('appointment/',views.appointment,name='appointment'),
    
]

project/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('accounts/',include('accounts.urls',namespace='accounts')),
    path('admin/', admin.site.urls),
    path('' , views.home , name = 'home'),
    path('courses/',include('course.urls',namespace='course')),
    path('about/',include('about.urls',namespace='about')),
    path('trainers/',include('trainers.urls',namespace='trainers')),
    path('pages/',include('pages.urls',namespace='pages')),
    path('contact/',include('contact.urls',namespace='contact')),
]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/includes/footer.html
<!-- Footer Start -->
<div class="container-fluid bg-dark text-light footer my-6 mb-0 py-6 wow fadeIn" data-wow-delay="0.1s">
    <div class="container">
        <div class="row g-5">
            <div class="col-lg-3 col-md-6">
                <h4 class="text-white mb-4">Get In Touch</h4>
                <h2 class="text-primary mb-4"><i class="fa fa-car text-white me-2"></i>Drivin</h2>
                <p class="mb-2"><i class="fa fa-map-marker-alt me-3"></i>123 Street, New York, USA</p>
                <p class="mb-2"><i class="fa fa-phone-alt me-3"></i>+012 345 67890</p>
                <p class="mb-2"><i class="fa fa-envelope me-3"></i>info@example.com</p>
            </div>
            <div class="col-lg-3 col-md-6">
                <h4 class="text-light mb-4">Quick Links</h4>
                <a class="btn btn-link" href="">About Us</a>
                <a class="btn btn-link" href="">Contact Us</a>
                <a class="btn btn-link" href="">Our Services</a>
                <a class="btn btn-link" href="">Terms & Condition</a>
                <a class="btn btn-link" href="">Support</a>
            </div>
            <div class="col-lg-3 col-md-6">
                <h4 class="text-light mb-4">Popular Links</h4>
                <a class="btn btn-link" href="">About Us</a>
                <a class="btn btn-link" href="">Contact Us</a>
                <a class="btn btn-link" href="">Our Services</a>
                <a class="btn btn-link" href="">Terms & Condition</a>
                <a class="btn btn-link" href="">Support</a>
            </div>
            <div class="col-lg-3 col-md-6">
                <h4 class="text-light mb-4">Newsletter</h4>
                <form action="">
                    <div class="input-group">
                        <input type="text" class="form-control p-3 border-0" placeholder="Your Email Address">
                        <button class="btn btn-primary">Sign Up</button>
                    </div>
                </form>
                <h6 class="text-white mt-4 mb-3">Follow Us</h6>
                <div class="d-flex pt-2">
                    <a class="btn btn-square btn-outline-light me-1" href=""><i class="fab fa-twitter"></i></a>
                    <a class="btn btn-square btn-outline-light me-1" href=""><i class="fab fa-facebook-f"></i></a>
                    <a class="btn btn-square btn-outline-light me-1" href=""><i class="fab fa-youtube"></i></a>
                    <a class="btn btn-square btn-outline-light me-0" href=""><i class="fab fa-linkedin-in"></i></a>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Footer End -->

templates/includes/nav.html
<!-- Navbar Start -->
<nav class="navbar navbar-expand-lg bg-white navbar-light sticky-top p-0">
    <a href="index.html" class="navbar-brand d-flex align-items-center border-end px-4 px-lg-5">
        <h2 class="m-0"><i class="fa fa-car text-primary me-2"></i>Drivin</h2>
    </a>
    <button type="button" class="navbar-toggler me-4" data-bs-toggle="collapse" data-bs-target="#navbarCollapse">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
        <div class="navbar-nav ms-auto p-4 p-lg-0">
            <a href="{% url "home" %}" class="nav-item nav-link active">Home</a>
            <a href="{% url "about:about" %}" class="nav-item nav-link">About</a>
            <a href="{% url "courses:course" %}" class="nav-item nav-link">Courses</a>
            <a href="{% url "trainers:trainers" %}" class="nav-item nav-link">Our Trainers</a>
            <div class="nav-item dropdown">
                <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">Pages</a>
                <div class="dropdown-menu bg-light m-0">
                    <a href="{% url "pages:features" %}" class="dropdown-item">Features</a>
                    <a href="{% url "pages:appointment" %}" class="dropdown-item">Appointment</a>
                    <a href="{% url "pages:write_comment" %}" class="dropdown-item">Apply Comment</a>
                    <a href="{% url "pages:testimonial" %}" class="dropdown-item">Testimonial</a>
                </div>
            </div>
            <a href="{% url "contact:contact" %}" class="nav-item nav-link">Contact</a>
        </div>
            {% if request.user.is_authenticated %}
                    <a href="{% url "accounts:profile" %}" class="nav-item nav-link">{{user}}</a>
            {% if profile.image %}
                    <img src="{{profile.image.url}}" alt="" style="width: 50px;height: 50px;border-radius: 40%;">
            {% endif %}
                    <a href="{% url "accounts:logout" %}" class="nav-item nav-link">Logout</a>
            {% else %}
                    <a href="{% url "accounts:login" %}" class="nav-item nav-link">Login</a>
                    <a href="{% url "accounts:register" %}" class="nav-item nav-link">Signup</a>
            {% endif %}
    </div>
</nav>
<!-- Navbar End -->